version: '3.9'

services:
  db:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: db_mmi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: nextjs
    environment:
      DATABASE_URL: postgres://root:123456789@db:5432/db_mmi
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev-db

volumes:
  postgres_data: